name             'germinator_base'
maintainer       'John Leacox'
license          'Apache 2'
description      'Base things needed by all Germinator recipes'
version          '0.1.0'
supports         'Linux'