name             'germinator-linux-apps'
maintainer       'John Leacox'
license          'Apache 2'
description      'Installs/Configures germinator-linux-apps'
version          '0.1.0'
supports         'Linux'
